# serial device, ttyS0 for Raspberry Pi 3, ttyAMA0 for older models
device: '/dev/ttyS0'

# database for logging
database: 'sqlite:///sensor_log.db'

# sensor name mapping
sensor_map:
    '1': 'Sensor 1'
    '2': 'Sensor 2'
    '3': 'Sensor 3'

# timezone shown in webgui
timezone: 'CET'

# darksky api key for outside temperature
darksky_api_key: null

# your location
lat_lon:
    - 50.0
    - 10.0

# get from pushover.net
pa_app_token: ''
pa_user_key: ''

# list of tuples: (sensor_id, [t or h], value, [+ or -] (for above or below)
# example [1, 't', 28.0, '+']
# alert at temperature over 28.0 at sensor 1
notification_constraints:
    - [1, 't', 28.0, '+']
    - [2, 'h', 60.0, '+']

